package io.github.lakehouseflow.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Immutable scheduler instruction published for one ready task instance.
 *
 * The row is also the durable database-outbox payload. It freezes the target
 * asset and baseline used by Lakehouse Flow to confirm the result solely from
 * later snapshot progression. No executor result or runtime callback belongs
 * to this model.
 */
@Entity
@Table(
    name = "scheduling_intent",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_scheduling_intent_key", columnNames = "intent_key"),
        @UniqueConstraint(name = "uk_scheduling_intent_task", columnNames = "task_instance_id")
    },
    indexes = {
        @Index(name = "idx_scheduling_intent_workflow", columnList = "workflow_instance_id,created_at ASC"),
        @Index(name = "idx_scheduling_intent_asset", columnList = "target_asset_key,created_at ASC")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SchedulingIntent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Version of the immutable downstream instruction contract. */
    @Column(name = "contract_version", nullable = false, updatable = false, length = 32)
    private String contractVersion;

    /** Stable idempotency key generated by Lakehouse Flow. */
    @Column(name = "intent_key", nullable = false, unique = true, updatable = false, length = 255)
    private String intentKey;

    /** Task scheduling decision represented by this instruction. */
    @Column(name = "task_instance_id", nullable = false, unique = true, updatable = false)
    private Long taskInstanceId;

    /** Owning workflow scheduling instance. */
    @Column(name = "workflow_instance_id", nullable = false, updatable = false)
    private Long workflowInstanceId;

    /** Trigger mode such as SNAPSHOT, SCHEDULE, BACKFILL, or MANUAL. */
    @Column(name = "trigger_type", nullable = false, updatable = false, length = 50)
    private String triggerType;

    /** Owning backfill batch when this instruction belongs to historical repair. */
    @Column(name = "backfill_batch_id", updatable = false)
    private Long backfillBatchId;

    /** Owning backfill item when this instruction belongs to historical repair. */
    @Column(name = "backfill_item_id", updatable = false)
    private Long backfillItemId;

    /** Immutable FlowPlanVersion anchor when the task came from a published graph. */
    @Column(name = "flow_plan_version_id", updatable = false)
    private Long flowPlanVersionId;

    /** Immutable ScheduleNode anchor when the task came from a published graph. */
    @Column(name = "schedule_node_id", updatable = false)
    private Long scheduleNodeId;

    /** Task or node code understood by the selected downstream integration. */
    @Column(name = "task_code", nullable = false, updatable = false, length = 255)
    private String taskCode;

    /** Task definition version copied into the immutable instruction. */
    @Column(name = "task_version", nullable = false, updatable = false)
    private Integer taskVersion;

    /** Business date represented by this scheduling instruction. */
    @Column(name = "biz_date", nullable = false, updatable = false)
    private LocalDateTime bizDate;

    /** Managed target asset whose snapshot progress confirms the result. */
    @Column(name = "target_asset_key", nullable = false, updatable = false, length = 255)
    private String targetAssetKey;

    /** Target snapshot observed immediately before first publication. */
    @Column(name = "baseline_snapshot_id", updatable = false, length = 255)
    private String baselineSnapshotId;

    /**
     * Complete versioned instruction consumed identically by database, HTTP,
     * and MQ delivery channels.
     */
    @Column(name = "instruction_payload_json", nullable = false, updatable = false, columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, Object> instructionPayloadJson;

    /** Time at which the immutable outbox instruction was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Initialize the immutable creation timestamp before insert. */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
