CREATE DATABASE IF NOT EXISTS commerce;

CREATE TABLE IF NOT EXISTS commerce.orders (
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount_cents BIGINT NOT NULL,
    order_date VARCHAR(10) NOT NULL,
    status VARCHAR(16) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (order_id)
);

GRANT SELECT, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'orders'@'%';
FLUSH PRIVILEGES;
